version: "3.8"

services:

  mongodb:
    image: mongo:5.0.2
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      mynetworkNode:
        ipv4_address: 174.19.0.2

  app:
    build: .
    restart: always
    env_file: ./.env
    volumes:
      - .:/app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # environment:
    #   - DB_HOST=mongodb
    #   - DB_USER=$MONGODB_USER
    #   - DB_PASSWORD=$MONGODB_PASSWORD
    #   - DB_NAME=$MONGODB_DATABASE
    #   - DB_PORT=$MONGODB_DOCKER_PORT
    networks:
      mynetworkNode:
        ipv4_address: 174.19.0.3

volumes:
  db:

networks:
  mynetworkNode:
    driver: bridge
    ipam:
      config:
      - subnet: 174.19.0.0/24
