version: "3.8"

services:
  app:
    build: .
    restart: always
    env_file: ./.env
    volumes:
      - .:/usr/src/app
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    links:
      - mongodatabase

  mongodatabase:
    image: mongo:5.0.2
    env_file: ./.env
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/data/db
    logging:
      driver: none

volumes:
  db:
